# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2dc2c3e0f13fcca8e511a8b083ec8e656f80f6124dcc32dd077b0259797a241dc1305c69f604541dc75f5382b35c7e0817c5e9b7d949cfa236d5c8b88a02d143

test:
  secret_key_base: 2808f9888d23ff727051f276a8892d28cf879aedda2140ca7385215655b5dde024da99cd5fa5a93d947bcf864c6d0722862fa484d24f48f2afd562297a92003f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
